All: TupleGeneratorVivado

TupleGeneratorVivado: Sources/TupleGenerator.vhd Sources/component.xml
	vivado -mode batch -source Create_project.tcl

clean:
	rm -fr TupleGeneratorVivado vivado.jou vivado.log Sources/ip Sources/ui

