/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef simple_switch_CONSTANTS_H
#define simple_switch_CONSTANTS_H

#include "simple_switch_types.h"

namespace sswitch_runtime {

class simple_switchConstants {
 public:
  simple_switchConstants();

};

extern const simple_switchConstants g_simple_switch_constants;

} // namespace

#endif
