/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "simple_switch_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace sswitch_runtime {

} // namespace
