#!/bin/bash -f
# Vivado (TM) v2017.1_sdx (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Jan 02 16:45:58 EST 2018
# IP Build 1908669 on Thu Jun 22 19:20:41 MDT 2017 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm gtwizard_ultrascale_v1_6_6 xxv_ethernet_v2_1_0 xlconstant_v1_1_3 util_vector_logic_v2_0_1 lib_cdc_v1_0_2 proc_sys_reset_v5_0_10 gigantic_mux generic_baseblocks_v2_1_0 fifo_generator_v13_1_4 axi_data_fifo_v2_1_11 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_12 axi_protocol_converter_v2_1_12 axi_clock_converter_v2_1_11 blk_mem_gen_v8_3_6 axi_dwidth_converter_v2_1_12 axis_infrastructure_v1_1_0 axis_data_fifo_v1_1_13 axis_clock_converter_v1_1_13 axis_register_slice_v1_1_11 axis_subset_converter_v1_1_11)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2017.1_sdx (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "/home/gyzuh/SDx/SDx/2017.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/gyzuh/SDx/SDx/2017.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/gyzuh/SDx/SDx/2017.1/Vivado/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/Deparser_t.HDL/Deparser_t.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/Deparser_t.HDL/Deparser_t.vp" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/Forward_t.HDL/Forward_t.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/Forward_t.HDL/Forward_t.vp" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/Parser_t.HDL/Parser_t.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/Parser_t.HDL/Parser_t.vp" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/RemoveHeaders_t.HDL/RemoveHeaders_t.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/RemoveHeaders_t.HDL/RemoveHeaders_t.vp" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_PROTOCOL_ADAPTERs.HDL/S_PROTOCOL_ADAPTER_EGRESS.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_PROTOCOL_ADAPTERs.HDL/S_PROTOCOL_ADAPTER_INGRESS.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_RESETTER.HDL/S_RESETTER_line.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_SYNCERs.HDL/S_SYNCER_for_Deparser.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_SYNCERs.HDL/S_SYNCER_for_RemoveHeaders.v" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_SYNCERs.HDL/S_SYNCER_for__OUT_.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_SYNCERs.HDL/xpm_cdc.sv" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_SYNCERs.HDL/xpm_fifo.sv" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/S_SYNCERs.HDL/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ipshared/1a28/XilinxSwitch.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_XilinxSwitch_0_0/sim/design_1_XilinxSwitch_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_6_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_bit_sync.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gte4_drp_arb.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gte4_delay_powergood.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtwiz_reset.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_reset_sync.v" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8785/hdl/gtwizard_ultrascale_v1_6_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/ip_0/sim/gtwizard_ultrascale_v1_6_gthe4_channel.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/ip_0/sim/design_1_xxv_ethernet_0_0_gt_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/ip_0/sim/gtwizard_ultrascale_v1_6_gthe4_common.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/ip_0/sim/design_1_xxv_ethernet_0_0_gt_gthe4_common_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/ip_0/sim/design_1_xxv_ethernet_0_0_gt_gtwizard_gthe4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/ip_0/sim/design_1_xxv_ethernet_0_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/ip_0/sim/design_1_xxv_ethernet_0_0_gt.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/xxv_ethernet_v2_1_0/design_1_xxv_ethernet_0_0_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/xxv_ethernet_v2_1_0/design_1_xxv_ethernet_0_0_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/xxv_ethernet_v2_1_0/design_1_xxv_ethernet_0_0_axi4_lite_if_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/xxv_ethernet_v2_1_0/design_1_xxv_ethernet_0_0_ultrascale_rx_userclk.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/xxv_ethernet_v2_1_0/design_1_xxv_ethernet_0_0_ultrascale_tx_userclk.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xxv_ethernet_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/e55a/hdl/xxv_ethernet_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xxv_ethernet_0_0/design_1_xxv_ethernet_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/45df/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/6d4d/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_0/sim/design_1_util_vector_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_10 $vhdlan_opts \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_1_0/sim/design_1_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_2_0/sim/design_1_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_3_0/sim/design_1_xlconstant_3_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_1_0/sim/design_1_util_vector_logic_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_2_0/sim/design_1_util_vector_logic_2_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gigantic_mux $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/c0d4/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/bd_f60c_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_1/sim/bd_f60c_g_inst_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/hdl/bd_f60c.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_4 $vhdlan_opts \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/5235/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e33/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/138d/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/c526/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/4158/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/fef9/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v1_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/a295/hdl/axis_data_fifo_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_clock_converter_v1_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/489c/hdl/axis_clock_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_cc_1/sim/design_1_auto_cc_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/09aa/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/hdl/tdata_design_1_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/hdl/tuser_design_1_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/hdl/tstrb_design_1_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/hdl/tkeep_design_1_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/hdl/tid_design_1_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/hdl/tdest_design_1_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/hdl/tlast_design_1_auto_ss_u_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/8a5f/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/acf8/hdl" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/d618/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/912b/hdl/verilog" +incdir+"$ref_dir/../../../../RSEInterface.srcs/sources_1/bd/design_1/ipshared/0e4e/hdl/verilog" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/hdl/top_design_1_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_1/sim/design_1_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/hdl/tdata_design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/hdl/tuser_design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/hdl/tstrb_design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/hdl/tkeep_design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/hdl/tid_design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/hdl/tdest_design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/hdl/tlast_design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/hdl/top_design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_si_r_0/sim/design_1_auto_ss_si_r_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_cc_0/sim/design_1_auto_cc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/hdl/tdata_design_1_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/hdl/tuser_design_1_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/hdl/tstrb_design_1_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/hdl/tkeep_design_1_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/hdl/tid_design_1_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/hdl/tdest_design_1_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/hdl/tlast_design_1_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/hdl/top_design_1_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ss_u_0/sim/design_1_auto_ss_u_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/hdl/design_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/gyzuh/University/DComp/Repository/P4Boosters/RSEInterface/RSEInterface.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
