#pragma line 1 "Encoder.c" ::: 0
#pragma line 1 "Encoder.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "Encoder.c" 2 ::: 194
#pragma line 1 "./rse.h" 1 ::: 195
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 204
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 232
#pragma line 122 "/usr/include/features.h" 3 4 ::: 329
#pragma line 156 "/usr/include/features.h" 3 4 ::: 354
#pragma line 180 "/usr/include/features.h" 3 4 ::: 356
#pragma line 191 "/usr/include/features.h" 3 4 ::: 359
#pragma line 343 "/usr/include/features.h" 3 4 ::: 390
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 394
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 429
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 436
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 459
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 500
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 506
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 524
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 530
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 534
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 536
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 540
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 550
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 603
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 644
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 669
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 693
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 694
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 696
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 698
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 699
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 724
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 735
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 740
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 741
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 742
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 748
#pragma line 56 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 789
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 792
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 794
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 822
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 824
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 826
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 887
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 894
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 912
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 917
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 928
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 997
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1011
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1014
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1015
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1047
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1063
#pragma line 56 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1088
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1091
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1096
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1118
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1139
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1142
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1153
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1163
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1165
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1169
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1218
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1219
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1225
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1227
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1247
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1258
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1299
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1329
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1355
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1359
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1374
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1386
#pragma line 107 "/usr/include/stdio.h" 3 4 ::: 1387
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1392
#pragma line 155 "/usr/include/stdio.h" 3 4 ::: 1414
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1425
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1442
#pragma line 190 "/usr/include/stdio.h" 3 4 ::: 1459
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1466
#pragma line 233 "/usr/include/stdio.h" 3 4 ::: 1469
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1480
#pragma line 330 "/usr/include/stdio.h" 3 4 ::: 1494
#pragma line 352 "/usr/include/stdio.h" 3 4 ::: 1503
#pragma line 421 "/usr/include/stdio.h" 3 4 ::: 1545
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1574
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1615
#pragma line 566 "/usr/include/stdio.h" 3 4 ::: 1632
#pragma line 618 "/usr/include/stdio.h" 3 4 ::: 1652
#pragma line 685 "/usr/include/stdio.h" 3 4 ::: 1674
#pragma line 745 "/usr/include/stdio.h" 3 4 ::: 1707
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1729
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1740
#pragma line 842 "/usr/include/stdio.h" 3 4 ::: 1747
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1760
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1784
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 1785
#pragma line 9 "./rse.h" 2 ::: 1788
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/time.h" 1 3 4 ::: 1789
#pragma line 25 "/usr/include/x86_64-linux-gnu/sys/time.h" 3 4 ::: 1806
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1807
#pragma line 74 "/usr/include/time.h" 3 4 ::: 1828
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/time.h" 2 3 4 ::: 1831
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 1833
#pragma line 28 "/usr/include/x86_64-linux-gnu/sys/time.h" 2 3 4 ::: 1868
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 1870
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 1901
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1924
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1926
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 1928
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1929
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 1933
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1973
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1984
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2005
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2013
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2015
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2037
#pragma line 89 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2070
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2072
#pragma line 126 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2085
#pragma line 30 "/usr/include/x86_64-linux-gnu/sys/time.h" 2 3 4 ::: 2087
#pragma line 63 "/usr/include/x86_64-linux-gnu/sys/time.h" 3 4 ::: 2088
#pragma line 90 "/usr/include/x86_64-linux-gnu/sys/time.h" 3 4 ::: 2099
#pragma line 10 "./rse.h" 2 ::: 2150
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 2151
#pragma line 43 "/usr/include/assert.h" 3 4 ::: 2172
#pragma line 68 "/usr/include/assert.h" 3 4 ::: 2177
#pragma line 100 "/usr/include/assert.h" 3 4 ::: 2193
#pragma line 11 "./rse.h" 2 ::: 2199
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2200
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2221
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2226
#pragma line 56 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2251
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2254
#pragma line 61 "/usr/include/string.h" 3 4 ::: 2275
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2284
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2287
#pragma line 175 "/usr/include/string.h" 3 4 ::: 2317
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2321
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2323
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2328
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2331
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2341
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2346
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2363
#pragma line 407 "/usr/include/string.h" 3 4 ::: 2367
#pragma line 444 "/usr/include/string.h" 3 4 ::: 2370
#pragma line 12 "./rse.h" 2 ::: 2374
#pragma line 2 "Encoder.c" 2 ::: 2457
