#pragma line 1 "Encoder.c" ::: -10
#pragma line 1 "Encoder.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "Encoder.c" 2 ::: 184
#pragma line 1 "./rse.h" 1 ::: 185
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 194
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 222
#pragma line 122 "/usr/include/features.h" 3 4 ::: 319
#pragma line 156 "/usr/include/features.h" 3 4 ::: 344
#pragma line 180 "/usr/include/features.h" 3 4 ::: 346
#pragma line 191 "/usr/include/features.h" 3 4 ::: 349
#pragma line 343 "/usr/include/features.h" 3 4 ::: 380
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 384
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 419
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 426
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 449
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 490
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 496
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 514
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 520
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 524
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 526
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 530
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 540
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 593
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 634
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 659
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 683
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 684
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 686
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 688
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 689
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 714
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 725
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 730
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 731
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 732
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 738
#pragma line 56 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 779
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 782
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 784
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 812
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 814
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 816
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 877
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 884
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 902
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 907
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 918
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 987
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1001
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1004
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1005
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1037
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1053
#pragma line 56 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1078
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1081
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1086
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1108
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1129
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1132
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1143
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1153
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1155
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1159
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1208
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1209
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1215
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1217
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1237
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1248
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1289
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1319
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1345
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1349
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1364
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1376
#pragma line 107 "/usr/include/stdio.h" 3 4 ::: 1377
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1382
#pragma line 155 "/usr/include/stdio.h" 3 4 ::: 1404
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1415
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1432
#pragma line 190 "/usr/include/stdio.h" 3 4 ::: 1449
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1456
#pragma line 233 "/usr/include/stdio.h" 3 4 ::: 1459
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1470
#pragma line 330 "/usr/include/stdio.h" 3 4 ::: 1484
#pragma line 352 "/usr/include/stdio.h" 3 4 ::: 1493
#pragma line 421 "/usr/include/stdio.h" 3 4 ::: 1535
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1564
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1605
#pragma line 566 "/usr/include/stdio.h" 3 4 ::: 1622
#pragma line 618 "/usr/include/stdio.h" 3 4 ::: 1642
#pragma line 685 "/usr/include/stdio.h" 3 4 ::: 1664
#pragma line 745 "/usr/include/stdio.h" 3 4 ::: 1697
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1719
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1730
#pragma line 842 "/usr/include/stdio.h" 3 4 ::: 1737
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1750
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1774
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 1775
#pragma line 9 "./rse.h" 2 ::: 1778
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/time.h" 1 3 4 ::: 1779
#pragma line 25 "/usr/include/x86_64-linux-gnu/sys/time.h" 3 4 ::: 1796
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1797
#pragma line 74 "/usr/include/time.h" 3 4 ::: 1818
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/time.h" 2 3 4 ::: 1821
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 1823
#pragma line 28 "/usr/include/x86_64-linux-gnu/sys/time.h" 2 3 4 ::: 1858
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 1860
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 1891
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1914
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1916
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 1918
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1919
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 1923
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 1963
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 1974
#pragma line 118 "/usr/include/time.h" 3 4 ::: 1995
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2003
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2005
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2027
#pragma line 89 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2060
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2062
#pragma line 126 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2075
#pragma line 30 "/usr/include/x86_64-linux-gnu/sys/time.h" 2 3 4 ::: 2077
#pragma line 63 "/usr/include/x86_64-linux-gnu/sys/time.h" 3 4 ::: 2078
#pragma line 90 "/usr/include/x86_64-linux-gnu/sys/time.h" 3 4 ::: 2089
#pragma line 10 "./rse.h" 2 ::: 2140
#pragma line 1 "/usr/include/assert.h" 1 3 4 ::: 2141
#pragma line 43 "/usr/include/assert.h" 3 4 ::: 2162
#pragma line 68 "/usr/include/assert.h" 3 4 ::: 2167
#pragma line 100 "/usr/include/assert.h" 3 4 ::: 2183
#pragma line 11 "./rse.h" 2 ::: 2189
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2190
#pragma line 29 "/usr/include/string.h" 3 4 ::: 2211
#pragma line 1 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2216
#pragma line 56 "/home/gyzuh/SDx/SDx/2017.1/Vivado_HLS/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2241
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2244
#pragma line 61 "/usr/include/string.h" 3 4 ::: 2265
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2274
#pragma line 124 "/usr/include/string.h" 3 4 ::: 2277
#pragma line 175 "/usr/include/string.h" 3 4 ::: 2307
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2311
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2313
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2318
#pragma line 278 "/usr/include/string.h" 3 4 ::: 2321
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2331
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2336
#pragma line 393 "/usr/include/string.h" 3 4 ::: 2353
#pragma line 407 "/usr/include/string.h" 3 4 ::: 2357
#pragma line 444 "/usr/include/string.h" 3 4 ::: 2360
#pragma line 12 "./rse.h" 2 ::: 2364
#pragma line 2 "Encoder.c" 2 ::: 2447
