set_property PACKAGE_PIN E4 [get_ports {gt_rtl_gtx_p[0]}]
set_property PACKAGE_PIN D2 [get_ports {gt_rtl_grx_p[0]}]
set_property PACKAGE_PIN D1 [get_ports {gt_rtl_grx_n[0]}]
set_property PACKAGE_PIN E3 [get_ports {gt_rtl_gtx_n[0]}]
set_property PACKAGE_PIN D6 [get_ports {gt_rtl_gtx_p[1]}]
set_property PACKAGE_PIN C4 [get_ports {gt_rtl_grx_p[1]}]
set_property PACKAGE_PIN C3 [get_ports {gt_rtl_grx_n[1]}]
set_property PACKAGE_PIN D5 [get_ports {gt_rtl_gtx_n[1]}]
set_property PACKAGE_PIN B6 [get_ports {gt_rtl_gtx_p[2]}]
set_property PACKAGE_PIN B2 [get_ports {gt_rtl_grx_p[2]}]
set_property PACKAGE_PIN B1 [get_ports {gt_rtl_grx_n[2]}]
set_property PACKAGE_PIN B5 [get_ports {gt_rtl_gtx_n[2]}]
set_property PACKAGE_PIN A8 [get_ports {gt_rtl_gtx_p[3]}]
set_property PACKAGE_PIN A4 [get_ports {gt_rtl_grx_p[3]}]
set_property PACKAGE_PIN A3 [get_ports {gt_rtl_grx_n[3]}]
set_property PACKAGE_PIN A7 [get_ports {gt_rtl_gtx_n[3]}]
set_property PACKAGE_PIN A12 [get_ports {sfp_tx_dis[0]}]
set_property PACKAGE_PIN A13 [get_ports {sfp_tx_dis[1]}]
set_property PACKAGE_PIN B13 [get_ports {sfp_tx_dis[2]}]
set_property PACKAGE_PIN C13 [get_ports {sfp_tx_dis[3]}]
set_property PACKAGE_PIN C7 [get_ports user_si570_sysclk_clk_n]
set_property PACKAGE_PIN C8 [get_ports user_si570_sysclk_clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp_tx_dis[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp_tx_dis[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp_tx_dis[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp_tx_dis[3]}]
create_clock -period 6.400 -name user_si570_sysclk_clk_p -waveform {0.000 3.200} [get_ports user_si570_sysclk_clk_p]

