// Code generated by the Fuselage Factory

// WE DISCOURAGE MODIFYING THIS FILE DIRECTLY!!!

`timescale 1 ps / 1 ps

module Decoder_0_t (
	clk_line,
	rst,
	packet_in_packet_in_SOF,
	packet_in_packet_in_EOF,
	packet_in_packet_in_VAL,
	packet_in_packet_in_RDY,
	packet_in_packet_in_DAT,
	packet_in_packet_in_CNT,
	packet_in_packet_in_ERR,
	packet_out_packet_out_SOF,
	packet_out_packet_out_EOF,
	packet_out_packet_out_VAL,
	packet_out_packet_out_RDY,
	packet_out_packet_out_DAT,
	packet_out_packet_out_CNT,
	packet_out_packet_out_ERR,
	tuple_in_control_VALID,
	tuple_in_control_DATA,
	tuple_out_control_VALID,
	tuple_out_control_DATA,
	tuple_in_Update_fl_VALID,
	tuple_in_Update_fl_DATA,
	tuple_out_Update_fl_VALID,
	tuple_out_Update_fl_DATA,
	tuple_in_hdr_VALID,
	tuple_in_hdr_DATA,
	tuple_out_hdr_VALID,
	tuple_out_hdr_DATA,
	tuple_in_ioports_VALID,
	tuple_in_ioports_DATA,
	tuple_out_ioports_VALID,
	tuple_out_ioports_DATA,
	tuple_in_local_state_VALID,
	tuple_in_local_state_DATA,
	tuple_out_local_state_VALID,
	tuple_out_local_state_DATA,
	tuple_in_Parser_extracts_VALID,
	tuple_in_Parser_extracts_DATA,
	tuple_out_Parser_extracts_VALID,
	tuple_out_Parser_extracts_DATA,
	tuple_in_Decoder_input_VALID,
	tuple_in_Decoder_input_DATA,
	tuple_out_Decoder_output_VALID,
	tuple_out_Decoder_output_DATA,
	backpressure_in,
	backpressure_out
);

input clk_line;
(* polarity = "high" *) input rst;
input packet_in_packet_in_SOF;
input packet_in_packet_in_EOF;
input packet_in_packet_in_VAL;
output packet_in_packet_in_RDY;
input [63:0] packet_in_packet_in_DAT;
input [3:0] packet_in_packet_in_CNT;
input packet_in_packet_in_ERR;
output packet_out_packet_out_SOF;
output packet_out_packet_out_EOF;
output packet_out_packet_out_VAL;
input packet_out_packet_out_RDY;
output [63:0] packet_out_packet_out_DAT;
output [3:0] packet_out_packet_out_CNT;
output packet_out_packet_out_ERR;
input tuple_in_control_VALID;
input [22:0] tuple_in_control_DATA;
output tuple_out_control_VALID;
output [22:0] tuple_out_control_DATA;
input tuple_in_Update_fl_VALID;
input [23:0] tuple_in_Update_fl_DATA;
output tuple_out_Update_fl_VALID;
output [23:0] tuple_out_Update_fl_DATA;
input tuple_in_hdr_VALID;
input [161:0] tuple_in_hdr_DATA;
output tuple_out_hdr_VALID;
output [161:0] tuple_out_hdr_DATA;
input tuple_in_ioports_VALID;
input [7:0] tuple_in_ioports_DATA;
output tuple_out_ioports_VALID;
output [7:0] tuple_out_ioports_DATA;
input tuple_in_local_state_VALID;
input [15:0] tuple_in_local_state_DATA;
output tuple_out_local_state_VALID;
output [15:0] tuple_out_local_state_DATA;
input tuple_in_Parser_extracts_VALID;
input [31:0] tuple_in_Parser_extracts_DATA;
output tuple_out_Parser_extracts_VALID;
output [31:0] tuple_out_Parser_extracts_DATA;
input tuple_in_Decoder_input_VALID;
input [16:0] tuple_in_Decoder_input_DATA;
output tuple_out_Decoder_output_VALID;
output [7:0] tuple_out_Decoder_output_DATA;
input backpressure_in;
output backpressure_out;

wire packet_in_packet_in_RDY;
wire packet_out_packet_out_SOF;
wire packet_out_packet_out_EOF;
wire packet_out_packet_out_VAL;
wire [63:0] packet_out_packet_out_DAT;
wire [3:0] packet_out_packet_out_CNT;
wire packet_out_packet_out_ERR;
wire tuple_out_control_VALID;
wire [22:0] tuple_out_control_DATA;
wire tuple_out_Update_fl_VALID;
wire [23:0] tuple_out_Update_fl_DATA;
wire tuple_out_hdr_VALID;
wire [161:0] tuple_out_hdr_DATA;
wire tuple_out_ioports_VALID;
wire [7:0] tuple_out_ioports_DATA;
wire tuple_out_local_state_VALID;
wire [15:0] tuple_out_local_state_DATA;
wire tuple_out_Parser_extracts_VALID;
wire [31:0] tuple_out_Parser_extracts_DATA;
wire tuple_out_Decoder_output_VALID;
wire [7:0] tuple_out_Decoder_output_DATA;

wire Decoder_ap_clk;
wire Decoder_ap_rst;
wire Decoder_ap_start;
wire Decoder_ap_done;
wire Decoder_ap_idle;
wire Decoder_ap_ready;
wire [281:0] Decoder_tuple_input_v_dout;
wire Decoder_tuple_input_v_empty_n;
wire Decoder_tuple_input_v_read;
wire [272:0] Decoder_tuple_output_v;
wire Decoder_tuple_output_v_ap_vld;
wire Decoder_tuple_output_v_ap_ack;
wire [70:0] Decoder_packet_input_v_dout;
wire Decoder_packet_input_v_empty_n;
wire Decoder_packet_input_v_read;
wire [70:0] Decoder_packet_output_v;
wire Decoder_packet_output_v_ap_vld;
wire Decoder_packet_output_v_ap_ack;

wire tuple_fifo_wr_en;
wire tuple_fifo_rd_en;
wire [281:0] tuple_fifo_din;
wire [281:0] tuple_fifo_dout;
wire tuple_fifo_empty;
wire tuple_fifo_almost_full;
wire tuple_fifo_full;

wire packet_fifo_wr_en;
wire packet_fifo_rd_en;
wire [70:0] packet_fifo_din;
wire [70:0] packet_fifo_dout;
wire packet_fifo_empty;
wire packet_fifo_almost_full;
wire packet_fifo_full;

Decoder Decoder_inst
(
  .ap_clk(Decoder_ap_clk),
  .ap_rst(Decoder_ap_rst),
  .ap_start(Decoder_ap_start),
  .ap_done(Decoder_ap_done),
  .ap_idle(Decoder_ap_idle),
  .ap_ready(Decoder_ap_ready),
  .Tuple_input_V_dout(Decoder_tuple_input_v_dout),
  .Tuple_input_V_empty_n(Decoder_tuple_input_v_empty_n),
  .Tuple_input_V_read(Decoder_tuple_input_v_read),
  .Tuple_output_V(Decoder_tuple_output_v),
  .Tuple_output_V_ap_vld(Decoder_tuple_output_v_ap_vld),
  .Tuple_output_V_ap_ack(Decoder_tuple_output_v_ap_ack),
  .Packet_input_V_dout(Decoder_packet_input_v_dout),
  .Packet_input_V_empty_n(Decoder_packet_input_v_empty_n),
  .Packet_input_V_read(Decoder_packet_input_v_read),
  .Packet_output_V(Decoder_packet_output_v),
  .Packet_output_V_ap_vld(Decoder_packet_output_v_ap_vld),
  .Packet_output_V_ap_ack(Decoder_packet_output_v_ap_ack)
);

assign Decoder_ap_clk = clk_line;
assign Decoder_ap_rst = rst;
assign Decoder_ap_start = 1;
assign Decoder_tuple_input_v_dout = tuple_fifo_dout;
assign Decoder_tuple_input_v_empty_n = ~tuple_fifo_empty;
assign Decoder_tuple_output_v_ap_ack = 1;
assign Decoder_packet_input_v_dout = packet_fifo_dout;
assign Decoder_packet_input_v_empty_n = ~packet_fifo_empty;
assign Decoder_packet_output_v_ap_ack = ~backpressure_in;

defparam tuple_fifo.WRITE_DATA_WIDTH = 282;
defparam tuple_fifo.FIFO_WRITE_DEPTH = 512;
defparam tuple_fifo.PROG_FULL_THRESH = 287;
defparam tuple_fifo.PROG_EMPTY_THRESH = 287;
defparam tuple_fifo.READ_MODE = "fwft";
defparam tuple_fifo.WR_DATA_COUNT_WIDTH = 9;
defparam tuple_fifo.RD_DATA_COUNT_WIDTH = 9;
defparam tuple_fifo.DOUT_RESET_VALUE = "0";
defparam tuple_fifo.FIFO_MEMORY_TYPE = "bram";

xpm_fifo_sync tuple_fifo (
	.wr_en(tuple_fifo_wr_en),
	.din(tuple_fifo_din),
	.rd_en(tuple_fifo_rd_en),
	.sleep(1'b0),
	.injectsbiterr(),
	.injectdbiterr(),
	.prog_empty(),
	.dout(tuple_fifo_dout), 
	.empty(tuple_fifo_empty), 
	.prog_full(tuple_fifo_almost_full),
	.full(tuple_fifo_full),
	.rd_data_count(),
	.wr_data_count(),
	.wr_rst_busy(),
	.rd_rst_busy(),
	.overflow(),
	.underflow(),
	.sbiterr(),
	.dbiterr(),
	.wr_clk(clk_line),
	.rst(rst)
);

assign tuple_fifo_wr_en = tuple_in_control_VALID;
assign tuple_fifo_din = {tuple_in_Decoder_input_DATA, tuple_in_Parser_extracts_DATA, tuple_in_local_state_DATA, tuple_in_ioports_DATA, tuple_in_hdr_DATA, tuple_in_Update_fl_DATA, tuple_in_control_DATA};
assign tuple_fifo_rd_en = Decoder_tuple_input_v_read;

defparam packet_fifo.WRITE_DATA_WIDTH = 71;
defparam packet_fifo.FIFO_WRITE_DEPTH = 512;
defparam packet_fifo.PROG_FULL_THRESH = 287;
defparam packet_fifo.PROG_EMPTY_THRESH = 287;
defparam packet_fifo.READ_MODE = "fwft";
defparam packet_fifo.WR_DATA_COUNT_WIDTH = 9;
defparam packet_fifo.RD_DATA_COUNT_WIDTH = 9;
defparam packet_fifo.DOUT_RESET_VALUE = "0";
defparam packet_fifo.FIFO_MEMORY_TYPE = "bram";

xpm_fifo_sync packet_fifo (
	.wr_en(packet_fifo_wr_en),
	.din(packet_fifo_din),
	.rd_en(packet_fifo_rd_en),
	.sleep(1'b0),
	.injectsbiterr(),
	.injectdbiterr(),
	.prog_empty(),
	.dout(packet_fifo_dout), 
	.empty(packet_fifo_empty), 
	.prog_full(packet_fifo_almost_full),
	.full(packet_fifo_full),
	.rd_data_count(),
	.wr_data_count(),
	.wr_rst_busy(),
	.rd_rst_busy(),
	.overflow(),
	.underflow(),
	.sbiterr(),
	.dbiterr(),
	.wr_clk(clk_line),
	.rst(rst)
);

assign packet_fifo_wr_en = packet_in_packet_in_VAL;
assign packet_fifo_din = {packet_in_packet_in_SOF, packet_in_packet_in_EOF, packet_in_packet_in_DAT,
                          packet_in_packet_in_CNT, packet_in_packet_in_ERR};
assign packet_fifo_rd_en = Decoder_packet_input_v_read;
assign packet_in_packet_in_RDY = 1;

assign {packet_out_packet_out_SOF, packet_out_packet_out_EOF, packet_out_packet_out_DAT,
        packet_out_packet_out_CNT, packet_out_packet_out_ERR} = Decoder_packet_output_v;
assign packet_out_packet_out_VAL = Decoder_packet_output_v_ap_vld & ~backpressure_in;

assign tuple_out_control_DATA  = Decoder_tuple_output_v[22:0];
assign tuple_out_Update_fl_DATA  = Decoder_tuple_output_v[46:23];
assign tuple_out_hdr_DATA  = Decoder_tuple_output_v[208:47];
assign tuple_out_ioports_DATA  = Decoder_tuple_output_v[216:209];
assign tuple_out_local_state_DATA  = Decoder_tuple_output_v[232:217];
assign tuple_out_Parser_extracts_DATA  = Decoder_tuple_output_v[264:233];
assign tuple_out_Decoder_output_DATA  = Decoder_tuple_output_v[272:265];

assign tuple_out_control_VALID  = Decoder_tuple_output_v_ap_vld;
assign tuple_out_Update_fl_VALID  = Decoder_tuple_output_v_ap_vld;
assign tuple_out_hdr_VALID  = Decoder_tuple_output_v_ap_vld;
assign tuple_out_ioports_VALID  = Decoder_tuple_output_v_ap_vld;
assign tuple_out_local_state_VALID  = Decoder_tuple_output_v_ap_vld;
assign tuple_out_Parser_extracts_VALID  = Decoder_tuple_output_v_ap_vld;
assign tuple_out_Decoder_output_VALID  = Decoder_tuple_output_v_ap_vld;

assign backpressure_out = packet_fifo_almost_full;

endmodule
