-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aesl_mux_load_4i368P is
port (
    empty : IN STD_LOGIC_VECTOR (1 downto 0);
    parity_buffer_3 : IN STD_LOGIC_VECTOR (367 downto 0);
    parity_buffer_0 : IN STD_LOGIC_VECTOR (367 downto 0);
    parity_buffer_1 : IN STD_LOGIC_VECTOR (367 downto 0);
    parity_buffer_2 : IN STD_LOGIC_VECTOR (367 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (367 downto 0) );
end;


architecture behav of aesl_mux_load_4i368P is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal sel_tmp_fu_46_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_72_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_58_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_52_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_64_p3 : STD_LOGIC_VECTOR (367 downto 0);
    signal newSel1_fu_78_p3 : STD_LOGIC_VECTOR (367 downto 0);


begin



    ap_return <= 
        newSel_fu_64_p3 when (or_cond_fu_72_p2(0) = '1') else 
        newSel1_fu_78_p3;
    newSel1_fu_78_p3 <= 
        parity_buffer_0 when (sel_tmp_fu_46_p2(0) = '1') else 
        parity_buffer_3;
    newSel_fu_64_p3 <= 
        parity_buffer_2 when (sel_tmp4_fu_58_p2(0) = '1') else 
        parity_buffer_1;
    or_cond_fu_72_p2 <= (sel_tmp4_fu_58_p2 or sel_tmp2_fu_52_p2);
    sel_tmp2_fu_52_p2 <= "1" when (empty = ap_const_lv2_1) else "0";
    sel_tmp4_fu_58_p2 <= "1" when (empty = ap_const_lv2_2) else "0";
    sel_tmp_fu_46_p2 <= "1" when (empty = ap_const_lv2_0) else "0";
end behav;
