set_property PACKAGE_PIN E4 [get_ports {gt_rtl_gtx_p[0]}]
set_property PACKAGE_PIN D2 [get_ports {gt_rtl_grx_p[0]}]
set_property PACKAGE_PIN D1 [get_ports {gt_rtl_grx_n[0]}]
set_property PACKAGE_PIN E3 [get_ports {gt_rtl_gtx_n[0]}]
set_property PACKAGE_PIN A12 [get_ports {sfp_tx_dis[0]}]
set_property PACKAGE_PIN C7 [get_ports gt_ref_clk_clk_n]
set_property PACKAGE_PIN C8 [get_ports gt_ref_clk_clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp_tx_dis[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
