set_property PACKAGE_PIN E4 [get_ports {gt_rtl_gtx_p[0]}]
set_property PACKAGE_PIN D2 [get_ports {gt_rtl_grx_p[0]}]
set_property PACKAGE_PIN D1 [get_ports {gt_rtl_grx_n[0]}]
set_property PACKAGE_PIN E3 [get_ports {gt_rtl_gtx_n[0]}]
set_property PACKAGE_PIN A12 [get_ports {sfp_tx_dis[0]}]
set_property PACKAGE_PIN C7 [get_ports user_si570_sysclk_clk_n]
set_property PACKAGE_PIN C8 [get_ports user_si570_sysclk_clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp_tx_dis[0]}]
create_clock -period 6.400 -name user_si570_sysclk_clk_p -waveform {0.000 3.200} [get_ports user_si570_sysclk_clk_p]

