all: compressorAndDecompressor

compressorAndDecompressor: compressorAndDecompressor.cpp
	g++ compressorAndDecompressor.cpp -o compressorAndDecompressor -lpcap -std=c++11

clean: 
	$(RM) compressorAndDecompressor
