All: RSEFeedbackVivado

RSEFeedbackVivado: Sources/RSEFeedback.vhd Sources/component.xml Sources/fifo_generator_0.xci
	vivado -mode batch -source Create_project.tcl

clean:
	rm -fr RSEFeedbackVivado vivado.jou vivado.log Sources/ip Sources/ui

