#!/bin/bash -e
BITSTREAM=../RSESDx/RSE_hardware/design_1_wrapper.bit
BSP=../RSESDx/RSE_BSP/psu_cortexa53_0/lib/libxil.a

source ${SDSOC_ROOT}/settings64.sh

if [ ${BITSTREAM} -nt ${BSP} ]
then
  echo "================================================================================"
  echo "Compile Board Support Package"
  echo "================================================================================"

  cd ../RSESDx/RSE_BSP
  make
  cd -
fi

echo
echo "================================================================================"
echo "Compile Initialization Software"
echo "================================================================================"

cd ../RSESDx/RSE_software/Debug
make
cd -

echo
echo "================================================================================"
echo "Program board"
echo "================================================================================"

sdx -batch -source ./Run.tcl

