#!/bin/bash -e
if [ "$EUID" -ne 0 ]
  then echo "Please run this script as root."
  exit 1
fi

INTERFACE=$(./Find_interface)
TEMP_FILE=$(mktemp)
tcpdump -i ${INTERFACE} -vvv -XX -Q in &> ${TEMP_FILE} &
PROCESS_ID=$!

echo "Input:"
tcpreplay --intf1=${INTERFACE} Encoded.pcap

sleep 1
kill "${PROCESS_ID}"

echo
echo "Output:"
cat "${TEMP_FILE}"

rm "${TEMP_FILE}"

