#!/bin/bash -e
echo
echo "================================================================================"
echo "Start TCPDump"
echo "================================================================================"

INTERFACE=$(./Find_interface)
echo "Board found on interface ${INTERFACE}."
TEMP_FILE=$(mktemp)
sudo tcpdump -i "${INTERFACE}" -vvv -XX -Q in &> "${TEMP_FILE}" &
PROCESS_ID=$!

# Make sure that TCPDump is ready to receive packets.
sleep 1

echo
echo "================================================================================"
echo "Send packets"
echo "================================================================================"
sudo tcpreplay "--intf1=${INTERFACE}" Encoded.pcap

# Make sure that we don't miss packets.
sleep 1

echo
echo "================================================================================"
echo "Receive packets"
echo "================================================================================"

# Send terminate signal to TCPDump process (instead of sudo process) to ensure that the summary
# is output.
sudo kill $(ps --ppid "${PROCESS_ID}" -o pid=)

# The terminate signal needs some time to propagate.
sleep 1

cat "${TEMP_FILE}"
rm "${TEMP_FILE}"

